/** 사용하기엔 이벤트가 많기에 적용은 보류 */
export type CommonEvent = {
  onMouseDown?: React.MouseEventHandler<HTMLElement> | undefined;
  onMouseUp?: React.MouseEventHandler<HTMLElement> | undefined;
  onClick?: React.MouseEventHandler<HTMLElement> | undefined;
  onDoubleClick?: React.MouseEventHandler<HTMLElement> | undefined;
  onMouseMove?: React.MouseEventHandler<HTMLElement> | undefined;
  onDrag?: React.MouseEventHandler<HTMLElement> | undefined;
  onBlur?: React.FocusEventHandler<HTMLElement> | undefined;
  onFocus?: React.FocusEventHandler<HTMLElement> | undefined;
  onFocusVisible?: (...args: Array<unknown>) => void | undefined;
  onDelete?: (...args: Array<unknown>) => void | undefined;
  onChange?: (...args: Array<unknown>) => void | undefined;
  onBackdropClick?: (...args: Array<unknown>) => void | undefined;
  onClose?: (...args: Array<unknown>) => void | undefined;
  onOpen?: (...args: Array<unknown>) => void | undefined;
  onKeyUp?: React.KeyboardEventHandler<HTMLElement> | undefined;
  onKeyPress?: React.KeyboardEventHandler<HTMLElement> | undefined;
  onSearchClick?: (...args: Array<unknown>) => void | undefined;
  onBtnTextClick?: (...args: Array<unknown>) => void | undefined;
  onMouseOver?: React.MouseEventHandler<HTMLElement> | undefined;
  onDrop?: React.MouseEventHandler<HTMLElement> | undefined;
  onHighlightChange?: (...args: Array<unknown>) => void | undefined;
  onInputChange?: (...args: Array<unknown>) => void | undefined;
  addEndListener?: (...args: Array<unknown>) => void | undefined;
  onEnter?: (...args: Array<unknown>) => void | undefined;
  onEntering?: (...args: Array<unknown>) => void | undefined;
  onEntered?: (...args: Array<unknown>) => void | undefined;
  onExit?: (...args: Array<unknown>) => void | undefined;
  onExiting?: (...args: Array<unknown>) => void | undefined;
  onExited?: (...args: Array<unknown>) => void | undefined;
  onClickAway?: (...args: Array<unknown>) => void | undefined;
  onChangeActive?: (...args: Array<unknown>) => void | undefined;
  onPageChange?: (...args: Array<unknown>) => void | undefined;
  onRowsPerPageChange?: (...args: Array<unknown>) => void | undefined;
  onCustomClick?: (...args: Array<unknown>) => void | undefined;
  onAccept?: (...args: Array<unknown>) => void | undefined;
  onError?: (...args: Array<unknown>) => void | undefined;
  onMonthChange?: (...args: Array<unknown>) => void | undefined;
  onViewChange?: (...args: Array<unknown>) => void | undefined;
  onYearChange?: (...args: Array<unknown>) => void | undefined;
  onDaySelect?: (...args: Array<unknown>) => void | undefined;
  onFocusedDayChange?: (...args: Array<unknown>) => void | undefined;
};
