name: test
on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: component test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        id: cache
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          cache: "npm"

      - name: Check module cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json')}}

      - name: Install modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Test component
        run: npm run test

      - name: Test when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          status: failure
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Test when success
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
