name: learn-github-actions
# 트리거로 push,pull-request 발생 시 이벤트 발생
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
    paths:
      - "**.js"
    paths-ignore:
      - "doc/**"
jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: My First Step
        runs: npm install
          npm test
          npm build
      - name: Cache yarn dependencies
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{runner.os}}-yarn-${{hashFiles('**/yarn.lock')}}
          restore-keys: |
            ${{runner.os}}-yarn
